### ISSUE TITLE
Unified Search

### ISSUE THREAD

**Issue by bflanagin** [open-orchard/ODESI#92]
# Story

A user wants to search for something within ODESI. User,app,developer,chat message, image(maybe), song, video, etc. 

# Thoughts
Right now we have several search features built into the API but a generalized single search function to return anything based on variables will give developers a more powerful way to work with ODESI.

# Tasks

- [x] Create Search function 
- [x] Create call that allows very fine-tuned options to give the developers a clear way to use it. 
- [x] Verify the returns always follow the return policies regardless to the search criteria.

**Comment by bflanagin** [comment]
The function is now ready for more use. Internally we will need to create new tasks for when new data needs to be searched.
